#!/bin/bash

case "$1" in
    refresh)
        if [ "$CONFIG_CORE" != cmc ] ; then
            echo -n "Updating precompiled host checks for Check_MK..."
            check_mk -C && echo OK || echo Failed
        fi
    ;;
esac
