{'edithost': {u'Basicsettings': 'on', u'Hosttags': 'on'},
 'nform': {u'ConfigurationGUI(WATO)': 'on',
           u'Deprecated': 'on',
           u'DiskspaceCleanup': 'on',
           u'Notification': 'on',
           u'OperationmodeofCheck_MK': 'on',
           u'Servicediscovery': 'on',
           u'StatusGUI(Multisite)': 'on'},
 'user': {u'ContactGroups': 'on', u'PersonalSettings': 'on'},
 'views': {u'Business Intelligence': 'on',
           u'Host Groups': 'on',
           u'Hosts': 'on',
           u'Other': 'on',
           u'Overview': 'on',
           u'Services': 'on'}}
