; Created by OMD hook MULTISITE_AUTHORISATION
; Use the permissions files generated by multisite
[global]
authorisationmodule="CoreAuthorisationModMultisite"
authorisation_multisite_file="/omd/sites/Mysite/var/check_mk/wato/auth/auth.php"
