#!/bin/sh

. "###ROOT###/.profile"

export PHP_FCGI_MAX_REQUESTS=1000

# Replace with the path to your FastCGI-enabled PHP executable
exec /usr/bin/php5-cgi \
    -d session.save_handler=files \
    -d session.save_path=###ROOT###/tmp/php/session \
    -d upload_tmp_dir=###ROOT###/tmp/php/upload \
    -d soap.wsdl_cache_dir=###ROOT###/tmp/php/wsdl-cache \
    -d safe_mode='Off' \
    -d mysql.default_socket=###ROOT###/tmp/run/mysqld/mysqld.sock
