# Written by WATO
# encoding: utf-8

all_hosts += [
  "ISBEventssrv.isb.edu|lan|prod|ping|wato|/" + FOLDER_PATH + "/",
  "ISBPGPSRV.isb.edu|lan|prod|ping|wato|/" + FOLDER_PATH + "/",
  "ISBSNGSRV1.isb.edu|lan|prod|ping|wato|/" + FOLDER_PATH + "/",
  "ISBSNGSRV2.isb.edu|lan|prod|ping|wato|/" + FOLDER_PATH + "/",
  "firewall-vlan1838.networklayer.com|lan|prod|ping|wato|/" + FOLDER_PATH + "/",
  "server06-new.isb.edu|lan|prod|ping|wato|/" + FOLDER_PATH + "/",
  "server10.isb.edu|lan|prod|ping|wato|/" + FOLDER_PATH + "/",
  "server11.isb.edu|lan|prod|ping|wato|/" + FOLDER_PATH + "/",
  "server3.isb.edu|lan|prod|ping|wato|/" + FOLDER_PATH + "/",
  "server5.isb.edu|lan|prod|ping|wato|/" + FOLDER_PATH + "/",
  "server7.isb.edu|lan|prod|ping|wato|/" + FOLDER_PATH + "/",
  "win1003539.cas1.isb.edu|lan|prod|ping|wato|/" + FOLDER_PATH + "/",
  "win13540.cas1.isb.edu|lan|prod|ping|wato|/" + FOLDER_PATH + "/",
  "win14758.sg13.isb.edu|lan|prod|ping|wato|/" + FOLDER_PATH + "/",
  "win14760.sg13.isb.edu|lan|prod|ping|wato|/" + FOLDER_PATH + "/",
  "win230.vhostdns.com|lan|prod|ping|wato|/" + FOLDER_PATH + "/",
]

# Explicit IP addresses
ipaddresses.update({'ISBEventssrv.isb.edu': u'216.12.199.11',
 'ISBPGPSRV.isb.edu': u'119.81.48.204',
 'ISBSNGSRV1.isb.edu': u'216.12.199.10',
 'ISBSNGSRV2.isb.edu': u'119.81.48.202',
 'firewall-vlan1838.networklayer.com': u'119.81.41.254',
 'server06-new.isb.edu': u'208.43.81.37',
 'server10.isb.edu': u'173.193.209.195',
 'server11.isb.edu': u'173.193.222.199',
 'server3.isb.edu': u'208.43.81.36',
 'server5.isb.edu': u'208.43.81.38',
 'server7.isb.edu': u'208.43.81.41',
 'win1003539.cas1.isb.edu': u'119.81.17.211',
 'win13540.cas1.isb.edu': u'119.81.17.213',
 'win14758.sg13.isb.edu': u'119.81.17.214',
 'win14760.sg13.isb.edu': u'119.81.48.203',
 'win230.vhostdns.com': u'67.228.207.220'})


# Settings for alias
extra_host_conf.setdefault('alias', []).extend(
  [(u'173.193.209.195', ['server10.isb.edu']),
 (u'173.193.222.199', ['server11.isb.edu']),
 (u'119.81.41.254', ['firewall-vlan1838.networklayer.com']),
 (u'119.81.48.204', ['ISBPGPSRV.isb.edu']),
 (u'119.81.48.203', ['win14760.sg13.isb.edu']),
 (u'208.43.81.36', ['server3.isb.edu']),
 (u'119.81.17.211', ['win1003539.cas1.isb.edu']),
 (u'208.43.81.38', ['server5.isb.edu']),
 (u'216.12.199.10', ['ISBSNGSRV1.isb.edu']),
 (u'119.81.17.214', ['win14758.sg13.isb.edu']),
 (u'216.12.199.11', ['ISBEventssrv.isb.edu']),
 (u'119.81.48.202', ['ISBSNGSRV2.isb.edu']),
 (u'208.43.81.37', ['server06-new.isb.edu']),
 (u'208.43.81.41', ['server7.isb.edu']),
 (u'67.228.207.220', ['win230.vhostdns.com']),
 (u'119.81.17.213', ['win13540.cas1.isb.edu'])])

# Host attributes (needed for WATO)
host_attributes.update(
{'ISBEventssrv.isb.edu': {'alias': u'216.12.199.11',
                          'contactgroups': {'groups': [],
                                            'recurse_perms': False,
                                            'recurse_use': False,
                                            'use': True},
                          'ipaddress': u'216.12.199.11',
                          'tag_agent': 'ping'},
 'ISBPGPSRV.isb.edu': {'alias': u'119.81.48.204',
                       'contactgroups': {'groups': [],
                                         'recurse_perms': False,
                                         'recurse_use': False,
                                         'use': True},
                       'ipaddress': u'119.81.48.204',
                       'tag_agent': 'ping'},
 'ISBSNGSRV1.isb.edu': {'alias': u'216.12.199.10',
                        'contactgroups': {'groups': [],
                                          'recurse_perms': False,
                                          'recurse_use': False,
                                          'use': True},
                        'ipaddress': u'216.12.199.10',
                        'tag_agent': 'ping'},
 'ISBSNGSRV2.isb.edu': {'alias': u'119.81.48.202',
                        'contactgroups': {'groups': [],
                                          'recurse_perms': False,
                                          'recurse_use': False,
                                          'use': True},
                        'ipaddress': u'119.81.48.202',
                        'tag_agent': 'ping'},
 'firewall-vlan1838.networklayer.com': {'alias': u'119.81.41.254',
                                        'contactgroups': {'groups': [],
                                                          'recurse_perms': False,
                                                          'recurse_use': False,
                                                          'use': True},
                                        'ipaddress': u'119.81.41.254',
                                        'tag_agent': 'ping'},
 'server06-new.isb.edu': {'alias': u'208.43.81.37',
                          'contactgroups': {'groups': [],
                                            'recurse_perms': False,
                                            'recurse_use': False,
                                            'use': True},
                          'ipaddress': u'208.43.81.37',
                          'tag_agent': 'ping'},
 'server10.isb.edu': {'alias': u'173.193.209.195',
                      'contactgroups': {'groups': [],
                                        'recurse_perms': False,
                                        'recurse_use': False,
                                        'use': True},
                      'ipaddress': u'173.193.209.195',
                      'tag_agent': 'ping'},
 'server11.isb.edu': {'alias': u'173.193.222.199',
                      'contactgroups': {'groups': [],
                                        'recurse_perms': False,
                                        'recurse_use': False,
                                        'use': True},
                      'ipaddress': u'173.193.222.199',
                      'tag_agent': 'ping'},
 'server3.isb.edu': {'alias': u'208.43.81.36',
                     'contactgroups': {'groups': [],
                                       'recurse_perms': False,
                                       'recurse_use': False,
                                       'use': True},
                     'ipaddress': u'208.43.81.36',
                     'tag_agent': 'ping'},
 'server5.isb.edu': {'alias': u'208.43.81.38',
                     'contactgroups': {'groups': [],
                                       'recurse_perms': False,
                                       'recurse_use': False,
                                       'use': True},
                     'ipaddress': u'208.43.81.38',
                     'tag_agent': 'ping'},
 'server7.isb.edu': {'alias': u'208.43.81.41',
                     'contactgroups': {'groups': [],
                                       'recurse_perms': False,
                                       'recurse_use': False,
                                       'use': True},
                     'ipaddress': u'208.43.81.41',
                     'tag_agent': 'ping'},
 'win1003539.cas1.isb.edu': {'alias': u'119.81.17.211',
                             'contactgroups': {'groups': [],
                                               'recurse_perms': False,
                                               'recurse_use': False,
                                               'use': True},
                             'ipaddress': u'119.81.17.211',
                             'tag_agent': 'ping'},
 'win13540.cas1.isb.edu': {'alias': u'119.81.17.213',
                           'contactgroups': {'groups': [],
                                             'recurse_perms': False,
                                             'recurse_use': False,
                                             'use': True},
                           'ipaddress': u'119.81.17.213',
                           'tag_agent': 'ping'},
 'win14758.sg13.isb.edu': {'alias': u'119.81.17.214',
                           'contactgroups': {'groups': [],
                                             'recurse_perms': False,
                                             'recurse_use': False,
                                             'use': True},
                           'ipaddress': u'119.81.17.214',
                           'tag_agent': 'ping'},
 'win14760.sg13.isb.edu': {'alias': u'119.81.48.203',
                           'contactgroups': {'groups': [],
                                             'recurse_perms': False,
                                             'recurse_use': False,
                                             'use': True},
                           'ipaddress': u'119.81.48.203',
                           'tag_agent': 'ping'},
 'win230.vhostdns.com': {'alias': u'67.228.207.220',
                         'contactgroups': {'groups': [],
                                           'recurse_perms': False,
                                           'recurse_use': False,
                                           'use': True},
                         'ipaddress': u'67.228.207.220',
                         'tag_agent': 'ping'}})
